version: "3.8"

services:
  web:
    build: backend
    container_name: star-burger-django
  frontend:
    build: frontend
    container_name: star-burger-frontend
  db:
    image: postgres
    container_name: star-burger-postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB-star_burger}
      - POSTGRES_USER=${POSTGRES_USER-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-postgres}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"