version: "3.8"

services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
      - bundles_volumes:/usr/src/app/bundles
    ports:
      - "8080:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  frontend:
    command: ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"
    volumes:
      - bundles_volumes:/usr/src/app/bundles
  db:
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  static_volume:
  postgres_dev_data:
  media_volume:
  bundles_volumes: