version: "3.8"

services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    ports:
      - "8080:8000"
    env_file:
      - ./.env
  db:
    env_file:
      - ./.env

volumes:
  static_volume:
  postgres_data:
  media_volume: