# Generated by Django 3.2 on 2022-01-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20220117_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NP', 'не обработан'), ('P', 'обработан'), ('D', 'доставлен')], default='NP', max_length=12, verbose_name='статус заказа'),
        ),
    ]
