# Generated by Django 3.2 on 2022-01-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CH', 'Наличностью'), ('CD', 'Электронно'), ('NS', 'Не указано')], db_index=True, default='NS', max_length=12, verbose_name='способ оплаты'),
        ),
    ]
