# Generated by Django 3.2 on 2022-01-17 13:50

from django.db import migrations


def add_order_items_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    items = OrderItem.objects.all()
    for item in items.iterator():
        item.price = item.quantity * item.product.price
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(add_order_items_price)
    ]
