# Generated by Django 3.2 on 2022-01-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NP', 'не обработан'), ('P', 'обработан'), ('D', 'доставлен')], db_index=True, default='NP', max_length=12, verbose_name='статус заказа'),
        ),
    ]
